<?php

namespace App\Services\CroReports\Generators;

use App\Enums\BookingStatusEnum;
use App\Models\User;
use App\Models\ticketBooking;
use App\Services\CroReports\Contracts\ReportGenerator;
use App\Services\Reports\Concerns\ExportsTabularReport;
use Illuminate\Database\Eloquent\Builder;
use Symfony\Component\HttpFoundation\Response;

class GuestListReport implements ReportGenerator
{
    use ExportsTabularReport;

    public function generate(User $user, array $fields, array $filters, string $format): Response
    {
        $croId = (int) $user->id;

        $query = ticketBooking::query()
            ->with(['user', 'event', 'ticketCategory', 'checkedInBy'])
            ->forCroQueue($croId)
            ->whereIn('status', BookingStatusEnum::retainedSaleStatuses())
            ->latest('ticket_bookings.created_at');

        $this->applyFilters($query, $filters, $croId);

        $records = $query->limit(5000)->get();
        $fieldKeys = $fields !== [] ? $fields : array_keys(config('cro_reports.reports.guest_list.fields', []));
        $fieldLabels = config('cro_reports.reports.guest_list.fields', []);

        $headers = [];
        foreach ($fieldKeys as $key) {
            $headers[] = $fieldLabels[$key] ?? $key;
        }

        $rows = $records->map(function (ticketBooking $booking) use ($fieldKeys) {
            $values = [
                'ticket_number' => $booking->ticket_number,
                'guest_name' => $this->userDisplayName($booking->user),
                'email' => $booking->user?->email ?? '',
                'event' => $booking->event?->filterLabel() ?? '—',
                'ticket_type' => $booking->ticketCategory?->name ?? 'General',
                'amount' => number_format((float) $booking->ticket_price, 2, '.', ''),
                'status' => $booking->displayStatusLabel(),
                'purchased_at' => $booking->created_at?->format('Y-m-d H:i') ?? '—',
                'checked_in' => $booking->isCheckedIn() ? 'Yes' : 'No',
                'checked_in_at' => $booking->checked_in_at?->format('Y-m-d H:i') ?? '—',
                'checked_in_by' => $this->userDisplayName($booking->checkedInBy),
            ];

            return array_map(fn ($key) => $values[$key] ?? '—', $fieldKeys);
        })->all();

        $title = 'CRO Guest List Report';

        if ($format === 'csv') {
            return $this->downloadCsv($title, $headers, $rows, 'cro-guest-list');
        }

        return $this->downloadPdfTable($title, $headers, $rows, 'cro-guest-list', [
            ['label' => 'Total rows', 'value' => count($rows)],
            ['label' => 'Generated by', 'value' => $this->userDisplayName($user)],
        ]);
    }

    /**
     * @param  array<string, mixed>  $filters
     */
    private function applyFilters(Builder $query, array $filters, int $croId): void
    {
        if (! empty($filters['event_id'])) {
            $query->where('event_id', (int) $filters['event_id']);
        }

        if (! empty($filters['status'])) {
            $query->where('status', $filters['status']);
        }

        if (($filters['check_in'] ?? null) === 'checked_in') {
            $query->whereNotNull('checked_in_at');
        } elseif (($filters['check_in'] ?? null) === 'not_checked_in') {
            $query->whereNull('checked_in_at');
        }

        if (! empty($filters['date_from'])) {
            $query->whereDate('ticket_bookings.created_at', '>=', $filters['date_from']);
        }

        if (! empty($filters['date_to'])) {
            $query->whereDate('ticket_bookings.created_at', '<=', $filters['date_to']);
        }

        $q = trim((string) ($filters['q'] ?? ''));
        if ($q !== '') {
            $query->where(function (Builder $inner) use ($q, $croId) {
                $inner->where('ticket_number', 'like', "%{$q}%")
                    ->orWhereHas('user', function (Builder $userQuery) use ($q) {
                        $userQuery->where('email', 'like', "%{$q}%")
                            ->orWhere('first_name', 'like', "%{$q}%")
                            ->orWhere('last_name', 'like', "%{$q}%");
                    })
                    ->orWhereHas('event', function (Builder $eventQuery) use ($q, $croId) {
                        $eventQuery->withTrashed()
                            ->assignedToCro($croId)
                            ->where('name', 'like', "%{$q}%");
                    });
            });
        }
    }
}
