<?php

namespace App\Services\CroReports\Generators;

use App\Enums\SupportTicketStatusEnum;
use App\Models\Inquiry;
use App\Models\User;
use App\Services\Reports\Concerns\ExportsTabularReport;
use App\Services\CroReports\Contracts\ReportGenerator;
use Illuminate\Database\Eloquent\Builder;
use Symfony\Component\HttpFoundation\Response;

class InquiriesReport implements ReportGenerator
{
    use ExportsTabularReport;

    public function generate(User $user, array $fields, array $filters, string $format): Response
    {
        $query = Inquiry::query()
            ->with(['user:id,first_name,last_name,email', 'event:id,name', 'assignee:id,first_name,last_name,email'])
            ->forCroQueue((int) $user->id)
            ->latest();

        $this->applyFilters($query, $filters, (int) $user->id);

        $records = $query->limit(5000)->get();
        $fieldKeys = $fields !== [] ? $fields : array_keys(config('cro_reports.reports.inquiries.fields', []));
        $fieldLabels = config('cro_reports.reports.inquiries.fields', []);

        $headers = [];
        foreach ($fieldKeys as $key) {
            $headers[] = $fieldLabels[$key] ?? $key;
        }

        $rows = $records->map(function (Inquiry $inquiry) use ($fieldKeys) {
            $values = [
                'id' => $inquiry->id,
                'subject' => $inquiry->subject,
                'user' => $this->userDisplayName($inquiry->user),
                'event' => $inquiry->event?->name ?? '—',
                'status' => $inquiry->status instanceof SupportTicketStatusEnum
                    ? $inquiry->status->label()
                    : (string) $inquiry->status,
                'assignee' => $this->userDisplayName($inquiry->assignee),
                'submitted_at' => optional($inquiry->created_at)?->format('Y-m-d H:i') ?? '—',
                'updated_at' => optional($inquiry->updated_at)?->format('Y-m-d H:i') ?? '—',
            ];

            return array_map(fn ($key) => $values[$key] ?? '—', $fieldKeys);
        })->all();

        $title = 'CRO Inquiries Report';

        if ($format === 'csv') {
            return $this->downloadCsv($title, $headers, $rows, 'cro-inquiries');
        }

        return $this->downloadPdfTable($title, $headers, $rows, 'cro-inquiries', [
            ['label' => 'Total rows', 'value' => count($rows)],
            ['label' => 'Generated by', 'value' => $this->userDisplayName($user)],
        ]);
    }

    /**
     * @param  array<string, mixed>  $filters
     */
    private function applyFilters(Builder $query, array $filters, int $croId): void
    {
        $q = trim((string) ($filters['q'] ?? ''));
        if ($q !== '') {
            $query->where(function (Builder $inner) use ($q) {
                $inner->where('subject', 'like', "%{$q}%")
                    ->orWhere('message', 'like', "%{$q}%")
                    ->orWhereHas('user', function (Builder $user) use ($q) {
                        $user->where('first_name', 'like', "%{$q}%")
                            ->orWhere('last_name', 'like', "%{$q}%")
                            ->orWhere('email', 'like', "%{$q}%");
                    });
            });
        }

        if (! empty($filters['status'])) {
            $query->where('status', $filters['status']);
        }

        if (! empty($filters['event_id'])) {
            $query->where('event_id', (int) $filters['event_id']);
        }

        $assignment = (string) ($filters['assignment'] ?? 'all');
        if (in_array($assignment, ['me', 'unassigned'], true)) {
            $query->assignmentFilter($assignment, $croId);
        }

        if (! empty($filters['date_from'])) {
            $query->whereDate('created_at', '>=', $filters['date_from']);
        }

        if (! empty($filters['date_to'])) {
            $query->whereDate('created_at', '<=', $filters['date_to']);
        }
    }
}
