<?php

namespace App\Services\CroReports\Generators;

use App\Enums\RefundRequestStatusEnum;
use App\Models\RefundRequest;
use App\Models\User;
use App\Services\Reports\Concerns\ExportsTabularReport;
use App\Services\CroReports\Contracts\ReportGenerator;
use Illuminate\Database\Eloquent\Builder;
use Symfony\Component\HttpFoundation\Response;

class RefundsReport implements ReportGenerator
{
    use ExportsTabularReport;

    public function generate(User $user, array $fields, array $filters, string $format): Response
    {
        $query = RefundRequest::query()
            ->with([
                'user:id,first_name,last_name,email',
                'reviewer:id,first_name,last_name,email',
                'ticketBooking:id,ticket_number,event_id',
                'ticketBooking.event:id,name',
            ])
            ->forCroQueue((int) $user->id)
            ->latest();

        $this->applyFilters($query, $filters);

        $records = $query->limit(5000)->get();
        $fieldKeys = $fields !== [] ? $fields : array_keys(config('cro_reports.reports.refunds.fields', []));
        $fieldLabels = config('cro_reports.reports.refunds.fields', []);

        $headers = [];
        foreach ($fieldKeys as $key) {
            $headers[] = $fieldLabels[$key] ?? $key;
        }

        $rows = $records->map(function (RefundRequest $refund) use ($fieldKeys) {
            $values = [
                'id' => $refund->id,
                'ticket_number' => $refund->ticketBooking?->ticket_number ?? '—',
                'user' => $this->userDisplayName($refund->user),
                'event' => $refund->ticketBooking?->event?->name ?? '—',
                'amount' => number_format((float) $refund->refund_amount, 2),
                'percentage' => $refund->refund_percentage.'%',
                'status' => $refund->status instanceof RefundRequestStatusEnum
                    ? $refund->status->label()
                    : (string) $refund->status,
                'reason' => $refund->reason ?: '—',
                'requested_at' => optional($refund->created_at)?->format('Y-m-d H:i') ?? '—',
                'reviewed_at' => optional($refund->reviewed_at)?->format('Y-m-d H:i') ?? '—',
                'reviewer' => $this->userDisplayName($refund->reviewer),
            ];

            return array_map(fn ($key) => $values[$key] ?? '—', $fieldKeys);
        })->all();

        $title = 'CRO Refund Requests Report';

        if ($format === 'csv') {
            return $this->downloadCsv($title, $headers, $rows, 'cro-refunds');
        }

        return $this->downloadPdfTable($title, $headers, $rows, 'cro-refunds', [
            ['label' => 'Total rows', 'value' => count($rows)],
            ['label' => 'Generated by', 'value' => $this->userDisplayName($user)],
        ]);
    }

    /**
     * @param  array<string, mixed>  $filters
     */
    private function applyFilters(Builder $query, array $filters): void
    {
        $q = trim((string) ($filters['q'] ?? ''));
        if ($q !== '') {
            $query->where(function (Builder $inner) use ($q) {
                $inner->where('reason', 'like', "%{$q}%")
                    ->orWhereHas('user', function (Builder $user) use ($q) {
                        $user->where('first_name', 'like', "%{$q}%")
                            ->orWhere('last_name', 'like', "%{$q}%")
                            ->orWhere('email', 'like', "%{$q}%");
                    })
                    ->orWhereHas('ticketBooking', function (Builder $booking) use ($q) {
                        $booking->where('ticket_number', 'like', "%{$q}%");
                    });
            });
        }

        if (! empty($filters['status'])) {
            $query->where('status', $filters['status']);
        }

        if (! empty($filters['event_id'])) {
            $eventId = (int) $filters['event_id'];
            $query->whereHas('ticketBooking', fn (Builder $booking) => $booking->where('event_id', $eventId));
        }

        if (! empty($filters['date_from'])) {
            $query->whereDate('created_at', '>=', $filters['date_from']);
        }

        if (! empty($filters['date_to'])) {
            $query->whereDate('created_at', '<=', $filters['date_to']);
        }
    }
}
