<?php

namespace App\Services\AdminReports\Generators;

use App\Enums\SupportTicketStatusEnum;
use App\Models\Complaint;
use App\Models\Inquiry;
use App\Models\User;
use App\Services\AdminReports\Contracts\ReportGenerator;
use App\Services\Reports\Concerns\ExportsTabularReport;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Collection;
use Symfony\Component\HttpFoundation\Response;

class SupportReport implements ReportGenerator
{
    use ExportsTabularReport;

    public function generate(User $user, array $fields, array $filters, string $format): Response
    {
        $ticketType = (string) ($filters['ticket_type'] ?? '');
        $rowsSource = collect();

        if ($ticketType !== 'complaint') {
            $inquiryQuery = Inquiry::query()
                ->with(['user:id,first_name,last_name,email', 'event:id,name', 'assignee:id,first_name,last_name,email'])
                ->latest();
            $this->applyCommonFilters($inquiryQuery, $filters);
            $rowsSource = $rowsSource->merge(
                $inquiryQuery->limit(2500)->get()->map(fn (Inquiry $inquiry) => [
                    'type' => 'Inquiry',
                    'id' => $inquiry->id,
                    'subject' => $inquiry->subject,
                    'user' => $this->userDisplayName($inquiry->user),
                    'context' => $inquiry->event?->name ?? '—',
                    'status' => $inquiry->status instanceof SupportTicketStatusEnum
                        ? $inquiry->status->label()
                        : (string) $inquiry->status,
                    'assignee' => $this->userDisplayName($inquiry->assignee),
                    'submitted_at' => $inquiry->created_at?->format('Y-m-d H:i') ?? '—',
                    'sort' => $inquiry->created_at?->timestamp ?? 0,
                ])
            );
        }

        if ($ticketType !== 'inquiry') {
            $complaintQuery = Complaint::query()
                ->with(['user:id,first_name,last_name,email', 'assignee:id,first_name,last_name,email'])
                ->latest();
            $this->applyCommonFilters($complaintQuery, $filters);
            $rowsSource = $rowsSource->merge(
                $complaintQuery->limit(2500)->get()->map(fn (Complaint $complaint) => [
                    'type' => 'Complaint',
                    'id' => $complaint->id,
                    'subject' => $complaint->subject,
                    'user' => $this->userDisplayName($complaint->user),
                    'context' => 'General',
                    'status' => $complaint->status instanceof SupportTicketStatusEnum
                        ? $complaint->status->label()
                        : (string) $complaint->status,
                    'assignee' => $this->userDisplayName($complaint->assignee),
                    'submitted_at' => $complaint->created_at?->format('Y-m-d H:i') ?? '—',
                    'sort' => $complaint->created_at?->timestamp ?? 0,
                ])
            );
        }

        /** @var Collection<int, array<string, mixed>> $sorted */
        $sorted = $rowsSource->sortByDesc('sort')->take(5000)->values();

        $fieldKeys = $fields !== [] ? $fields : array_keys(config('admin_reports.reports.support.fields', []));
        $fieldLabels = config('admin_reports.reports.support.fields', []);

        $headers = [];
        foreach ($fieldKeys as $key) {
            $headers[] = $fieldLabels[$key] ?? $key;
        }

        $rows = $sorted->map(function (array $row) use ($fieldKeys) {
            return array_map(fn ($key) => $row[$key] ?? '—', $fieldKeys);
        })->all();

        $title = 'Admin Support Tickets Report';

        if ($format === 'csv') {
            return $this->downloadCsv($title, $headers, $rows, 'admin-support');
        }

        return $this->downloadPdfTable($title, $headers, $rows, 'admin-support', [
            ['label' => 'Total rows', 'value' => count($rows)],
            ['label' => 'Generated by', 'value' => $this->userDisplayName($user)],
        ]);
    }

    /**
     * @param  array<string, mixed>  $filters
     */
    private function applyCommonFilters(Builder $query, array $filters): void
    {
        $q = trim((string) ($filters['q'] ?? ''));
        if ($q !== '') {
            $query->where(function (Builder $inner) use ($q) {
                $inner->where('subject', 'like', "%{$q}%")
                    ->orWhere('message', 'like', "%{$q}%")
                    ->orWhereHas('user', function (Builder $userQuery) use ($q) {
                        $userQuery->where('email', 'like', "%{$q}%")
                            ->orWhere('first_name', 'like', "%{$q}%")
                            ->orWhere('last_name', 'like', "%{$q}%");
                    });
            });
        }

        if (! empty($filters['status'])) {
            $query->where('status', $filters['status']);
        }

        if (! empty($filters['cro_id'])) {
            $query->where('assigned_to', (int) $filters['cro_id']);
        }

        if (! empty($filters['date_from'])) {
            $query->whereDate('created_at', '>=', $filters['date_from']);
        }

        if (! empty($filters['date_to'])) {
            $query->whereDate('created_at', '<=', $filters['date_to']);
        }
    }
}
