<?php

namespace App\Services\AdminReports\Generators;

use App\Enums\BookingStatusEnum;
use App\Models\User;
use App\Models\ticketCategory;
use App\Services\AdminReports\Contracts\ReportGenerator;
use App\Services\Reports\Concerns\ExportsTabularReport;
use Illuminate\Database\Eloquent\Builder;
use Symfony\Component\HttpFoundation\Response;

class TicketCategoriesReport implements ReportGenerator
{
    use ExportsTabularReport;

    public function generate(User $user, array $fields, array $filters, string $format): Response
    {
        $query = ticketCategory::query()
            ->with(['event:id,name,created_by', 'event.organizer:id,first_name,last_name,email'])
            ->withCount([
                'ticketBookings as sold_count' => fn (Builder $q) => $q->whereIn(
                    'status',
                    BookingStatusEnum::retainedSaleStatuses()
                ),
            ])
            ->withSum([
                'ticketBookings as revenue_sum' => fn (Builder $q) => $q->whereIn(
                    'status',
                    BookingStatusEnum::retainedSaleStatuses()
                ),
            ], 'ticket_price')
            ->orderBy('event_id')
            ->orderBy('name');

        $this->applyFilters($query, $filters);

        $records = $query->limit(5000)->get();
        $fieldKeys = $fields !== [] ? $fields : array_keys(config('admin_reports.reports.ticket_categories.fields', []));
        $fieldLabels = config('admin_reports.reports.ticket_categories.fields', []);

        $headers = [];
        foreach ($fieldKeys as $key) {
            $headers[] = $fieldLabels[$key] ?? $key;
        }

        $rows = $records->map(function (ticketCategory $category) use ($fieldKeys) {
            $values = [
                'id' => $category->id,
                'event' => $category->event?->name ?? '—',
                'organizer' => $this->userDisplayName($category->event?->organizer),
                'name' => $category->name,
                'price' => number_format((float) $category->ticket_price, 2, '.', ''),
                'capacity' => (int) ($category->no_of_tickets ?? 0),
                'available' => (int) ($category->no_of_available_tickets ?? 0),
                'sold' => (int) ($category->sold_count ?? 0),
                'revenue' => number_format((float) ($category->revenue_sum ?? 0), 2, '.', ''),
                'is_active' => $category->is_active ? 'Yes' : 'No',
                'booking_start' => $category->booking_start?->format('Y-m-d H:i') ?? '—',
                'booking_end' => $category->booking_end?->format('Y-m-d H:i') ?? '—',
            ];

            return array_map(fn ($key) => $values[$key] ?? '—', $fieldKeys);
        })->all();

        $title = 'Admin Ticket Categories Report';

        if ($format === 'csv') {
            return $this->downloadCsv($title, $headers, $rows, 'admin-ticket-categories');
        }

        return $this->downloadPdfTable($title, $headers, $rows, 'admin-ticket-categories', [
            ['label' => 'Total rows', 'value' => count($rows)],
            ['label' => 'Generated by', 'value' => $this->userDisplayName($user)],
        ]);
    }

    /**
     * @param  array<string, mixed>  $filters
     */
    private function applyFilters(Builder $query, array $filters): void
    {
        $q = trim((string) ($filters['q'] ?? ''));
        if ($q !== '') {
            $query->where(function (Builder $inner) use ($q) {
                $inner->where('name', 'like', "%{$q}%")
                    ->orWhere('description', 'like', "%{$q}%")
                    ->orWhereHas('event', fn (Builder $event) => $event->where('name', 'like', "%{$q}%"));
            });
        }

        if (! empty($filters['event_id'])) {
            $query->where('event_id', (int) $filters['event_id']);
        }

        if (! empty($filters['organizer_id'])) {
            $query->whereHas('event', fn (Builder $event) => $event->where('created_by', (int) $filters['organizer_id']));
        }

        if (isset($filters['active']) && $filters['active'] !== '') {
            $query->where('is_active', (bool) (int) $filters['active']);
        }
    }
}
