<?php

namespace App\Services\AdminReports\Generators;

use App\Models\User;
use App\Services\AdminReports\Contracts\ReportGenerator;
use App\Services\Reports\Concerns\ExportsTabularReport;
use Illuminate\Database\Eloquent\Builder;
use Symfony\Component\HttpFoundation\Response;

class UsersReport implements ReportGenerator
{
    use ExportsTabularReport;

    public function generate(User $user, array $fields, array $filters, string $format): Response
    {
        $query = User::query()
            ->with('userRole')
            ->latest();

        $this->applyFilters($query, $filters);

        $records = $query->limit(5000)->get();
        $fieldKeys = $fields !== [] ? $fields : array_keys(config('admin_reports.reports.users.fields', []));
        $fieldLabels = config('admin_reports.reports.users.fields', []);

        $headers = [];
        foreach ($fieldKeys as $key) {
            $headers[] = $fieldLabels[$key] ?? $key;
        }

        $rows = $records->map(function (User $record) use ($fieldKeys) {
            $values = [
                'id' => $record->id,
                'first_name' => $record->first_name ?? '',
                'last_name' => $record->last_name ?? '',
                'email' => $record->email ?? '',
                'role' => $record->userRole?->name_en ?? '—',
                'contact_number' => $record->contact_number ?? '—',
                'is_active' => $record->is_active ? 'Yes' : 'No',
                'is_locked' => $record->is_locked ? 'Yes' : 'No',
                'created_at' => $record->created_at?->format('Y-m-d H:i') ?? '—',
            ];

            return array_map(fn ($key) => $values[$key] ?? '—', $fieldKeys);
        })->all();

        $title = 'Admin Users Report';

        if ($format === 'csv') {
            return $this->downloadCsv($title, $headers, $rows, 'admin-users');
        }

        return $this->downloadPdfTable($title, $headers, $rows, 'admin-users', [
            ['label' => 'Total rows', 'value' => count($rows)],
            ['label' => 'Generated by', 'value' => $this->userDisplayName($user)],
        ]);
    }

    /**
     * @param  array<string, mixed>  $filters
     */
    private function applyFilters(Builder $query, array $filters): void
    {
        $q = trim((string) ($filters['q'] ?? ''));
        if ($q !== '') {
            $query->where(function (Builder $inner) use ($q) {
                $inner->where('first_name', 'like', "%{$q}%")
                    ->orWhere('last_name', 'like', "%{$q}%")
                    ->orWhere('email', 'like', "%{$q}%")
                    ->orWhere('nic', 'like', "%{$q}%")
                    ->orWhere('contact_number', 'like', "%{$q}%");
            });
        }

        if (! empty($filters['role_id'])) {
            $query->where('role_id', (int) $filters['role_id']);
        }

        $state = (string) ($filters['state'] ?? '');
        if ($state === 'active') {
            $query->where('is_active', true)->where('is_locked', false);
        } elseif ($state === 'inactive') {
            $query->where('is_active', false);
        } elseif ($state === 'locked') {
            $query->where('is_locked', true);
        }

        if (! empty($filters['date_from'])) {
            $query->whereDate('created_at', '>=', $filters['date_from']);
        }

        if (! empty($filters['date_to'])) {
            $query->whereDate('created_at', '<=', $filters['date_to']);
        }
    }
}
