<?php

namespace App\Services\OrganizerReports\Generators;

use App\Enums\BookingStatusEnum;
use App\Models\ticketBooking;
use App\Models\User;
use App\Services\OrganizerReports\Contracts\ReportGenerator;
use App\Services\Reports\Concerns\ExportsTabularReport;
use Illuminate\Database\Eloquent\Builder;
use Symfony\Component\HttpFoundation\Response;

class AttendeesReport implements ReportGenerator
{
    use ExportsTabularReport;

    public function generate(User $user, array $fields, array $filters, string $format): Response
    {
        $query = ticketBooking::query()
            ->with(['user:id,first_name,last_name,email', 'event:id,name'])
            ->whereHas('event', fn (Builder $q) => $q->createdByOrganizer((int) $user->id))
            ->whereIn('status', BookingStatusEnum::retainedSaleStatuses());

        $this->applyFilters($query, $filters);

        $bookings = $query->limit(10000)->get();

        $grouped = $bookings->groupBy('user_id')->map(function ($group) {
            /** @var \Illuminate\Support\Collection<int, ticketBooking> $group */
            $first = $group->first();
            $user = $first?->user;
            $events = $group->pluck('event.name')->filter()->unique()->values();

            return [
                'name' => $this->userDisplayName($user),
                'email' => $user?->email ?? '—',
                'tickets' => $group->count(),
                'events' => $events->implode(', ') ?: '—',
                'total_spent' => number_format((float) $group->sum('ticket_price'), 2, '.', ''),
                'first_purchase' => optional($group->min('created_at'))?->format('Y-m-d H:i') ?? '—',
                'last_purchase' => optional($group->max('created_at'))?->format('Y-m-d H:i') ?? '—',
            ];
        })->sortByDesc('tickets')->values();

        $fieldKeys = $fields !== [] ? $fields : array_keys(config('organizer_reports.reports.attendees.fields', []));
        $fieldLabels = config('organizer_reports.reports.attendees.fields', []);

        $headers = [];
        foreach ($fieldKeys as $key) {
            $headers[] = $fieldLabels[$key] ?? $key;
        }

        $rows = $grouped->map(function (array $row) use ($fieldKeys) {
            return array_map(fn ($key) => $row[$key] ?? '—', $fieldKeys);
        })->all();

        $title = 'Organizer Attendees Report';

        if ($format === 'csv') {
            return $this->downloadCsv($title, $headers, $rows, 'organizer-attendees');
        }

        return $this->downloadPdfTable($title, $headers, $rows, 'organizer-attendees', [
            ['label' => 'Total attendees', 'value' => count($rows)],
            ['label' => 'Generated by', 'value' => $this->userDisplayName($user)],
        ]);
    }

    /**
     * @param  array<string, mixed>  $filters
     */
    private function applyFilters(Builder $query, array $filters): void
    {
        if (! empty($filters['event_id'])) {
            $query->where('event_id', (int) $filters['event_id']);
        }

        if (! empty($filters['date_from'])) {
            $query->whereDate('ticket_bookings.created_at', '>=', $filters['date_from']);
        }

        if (! empty($filters['date_to'])) {
            $query->whereDate('ticket_bookings.created_at', '<=', $filters['date_to']);
        }

        $q = trim((string) ($filters['q'] ?? ''));
        if ($q !== '') {
            $query->whereHas('user', function (Builder $user) use ($q) {
                $user->where('first_name', 'like', "%{$q}%")
                    ->orWhere('last_name', 'like', "%{$q}%")
                    ->orWhere('email', 'like', "%{$q}%");
            });
        }
    }
}
