<?php

namespace App\Services\OrganizerReports\Generators;

use App\Enums\BookingStatusEnum;
use App\Models\User;
use App\Models\ticketBooking;
use App\Services\OrganizerReports\Contracts\ReportGenerator;
use App\Services\Reports\Concerns\ExportsTabularReport;
use Illuminate\Database\Eloquent\Builder;
use Symfony\Component\HttpFoundation\Response;

class BookingsReport implements ReportGenerator
{
    use ExportsTabularReport;

    public function generate(User $user, array $fields, array $filters, string $format): Response
    {
        $query = ticketBooking::query()
            ->with(['user', 'event', 'ticketCategory', 'checkedInBy'])
            ->whereHas('event', fn (Builder $q) => $q->createdByOrganizer((int) $user->id))
            ->whereIn('status', BookingStatusEnum::retainedSaleStatuses())
            ->latest('ticket_bookings.created_at');

        $this->applyFilters($query, $filters);

        $records = $query->limit(5000)->get();
        $fieldKeys = $fields !== [] ? $fields : array_keys(config('organizer_reports.reports.bookings.fields', []));
        $fieldLabels = config('organizer_reports.reports.bookings.fields', []);

        $headers = [];
        foreach ($fieldKeys as $key) {
            $headers[] = $fieldLabels[$key] ?? $key;
        }

        $rows = $records->map(function (ticketBooking $booking) use ($fieldKeys) {
            $values = [
                'ticket_number' => $booking->ticket_number,
                'guest_name' => $booking->user?->full_name ?? 'Unknown',
                'email' => $booking->user?->email ?? '',
                'event' => $booking->event?->name ?? '—',
                'ticket_type' => $booking->ticketCategory?->name ?? 'General',
                'amount' => number_format((float) $booking->ticket_price, 2, '.', ''),
                'status' => $booking->displayStatusLabel(),
                'purchased_at' => $booking->created_at?->format('Y-m-d H:i') ?? '—',
                'checked_in' => $booking->isCheckedIn() ? 'Yes' : 'No',
                'checked_in_at' => $booking->checked_in_at?->format('Y-m-d H:i') ?? '—',
            ];

            return array_map(fn ($key) => $values[$key] ?? '—', $fieldKeys);
        })->all();

        $title = 'Organizer Guest List Report';

        if ($format === 'csv') {
            return $this->downloadCsv($title, $headers, $rows, 'organizer-guest-list');
        }

        return $this->downloadPdfTable($title, $headers, $rows, 'organizer-guest-list', [
            ['label' => 'Total rows', 'value' => count($rows)],
            ['label' => 'Generated by', 'value' => $this->userDisplayName($user)],
        ]);
    }

    /**
     * @param  array<string, mixed>  $filters
     */
    private function applyFilters(Builder $query, array $filters): void
    {
        if (! empty($filters['event_id'])) {
            $query->where('event_id', (int) $filters['event_id']);
        }

        if (! empty($filters['status'])) {
            $query->where('status', $filters['status']);
        }

        if (($filters['check_in'] ?? null) === 'checked_in') {
            $query->whereNotNull('checked_in_at');
        } elseif (($filters['check_in'] ?? null) === 'not_checked_in') {
            $query->whereNull('checked_in_at');
        }

        if (! empty($filters['date_from'])) {
            $query->whereDate('ticket_bookings.created_at', '>=', $filters['date_from']);
        }

        if (! empty($filters['date_to'])) {
            $query->whereDate('ticket_bookings.created_at', '<=', $filters['date_to']);
        }

        $q = trim((string) ($filters['q'] ?? ''));
        if ($q !== '') {
            $query->where(function (Builder $inner) use ($q) {
                $inner->where('ticket_number', 'like', "%{$q}%")
                    ->orWhereHas('user', function (Builder $userQuery) use ($q) {
                        $userQuery->where('email', 'like', "%{$q}%")
                            ->orWhere('first_name', 'like', "%{$q}%")
                            ->orWhere('last_name', 'like', "%{$q}%");
                    })
                    ->orWhereHas('event', function (Builder $eventQuery) use ($q) {
                        $eventQuery->where('name', 'like', "%{$q}%");
                    });
            });
        }
    }
}
