<?php

namespace App\Services\OrganizerReports\Generators;

use App\Enums\BookingStatusEnum;
use App\Models\Event;
use App\Models\User;
use App\Services\OrganizerReports\Contracts\ReportGenerator;
use App\Services\Reports\Concerns\ExportsTabularReport;
use Illuminate\Database\Eloquent\Builder;
use Symfony\Component\HttpFoundation\Response;

class EventsReport implements ReportGenerator
{
    use ExportsTabularReport;

    public function generate(User $user, array $fields, array $filters, string $format): Response
    {
        $query = Event::query()
            ->createdByOrganizer((int) $user->id)
            ->withCount([
                'ticketBookings as tickets_sold' => fn (Builder $q) => $q->whereIn(
                    'status',
                    BookingStatusEnum::retainedSaleStatuses()
                ),
            ])
            ->withSum([
                'ticketBookings as revenue_sum' => fn (Builder $q) => $q->whereIn(
                    'status',
                    BookingStatusEnum::retainedSaleStatuses()
                ),
            ], 'ticket_price')
            ->orderByDesc('date');

        $this->applyFilters($query, $filters);

        $records = $query->limit(2000)->get();
        $fieldKeys = $fields !== [] ? $fields : array_keys(config('organizer_reports.reports.events.fields', []));
        $fieldLabels = config('organizer_reports.reports.events.fields', []);

        $headers = [];
        foreach ($fieldKeys as $key) {
            $headers[] = $fieldLabels[$key] ?? $key;
        }

        $rows = $records->map(function (Event $event) use ($fieldKeys) {
            $values = [
                'id' => $event->id,
                'name' => $event->name,
                'status' => ucfirst((string) $event->status),
                'date' => is_string($event->date) ? $event->date : (optional($event->date)->format('Y-m-d') ?? '—'),
                'location' => $event->place ?? '—',
                'tickets_sold' => (int) ($event->tickets_sold ?? 0),
                'revenue' => number_format((float) ($event->revenue_sum ?? 0), 2, '.', ''),
                'created_at' => $event->created_at?->format('Y-m-d H:i') ?? '—',
            ];

            return array_map(fn ($key) => $values[$key] ?? '—', $fieldKeys);
        })->all();

        $title = 'Organizer Events Report';

        if ($format === 'csv') {
            return $this->downloadCsv($title, $headers, $rows, 'organizer-events');
        }

        return $this->downloadPdfTable($title, $headers, $rows, 'organizer-events', [
            ['label' => 'Total rows', 'value' => count($rows)],
            ['label' => 'Generated by', 'value' => $this->userDisplayName($user)],
        ]);
    }

    /**
     * @param  array<string, mixed>  $filters
     */
    private function applyFilters(Builder $query, array $filters): void
    {
        $q = trim((string) ($filters['q'] ?? ''));
        if ($q !== '') {
            $query->where(function (Builder $inner) use ($q) {
                $inner->where('name', 'like', "%{$q}%")
                    ->orWhere('place', 'like', "%{$q}%");
            });
        }

        if (! empty($filters['status'])) {
            $query->where('status', $filters['status']);
        }

        if (! empty($filters['date_from'])) {
            $query->whereDate('date', '>=', $filters['date_from']);
        }

        if (! empty($filters['date_to'])) {
            $query->whereDate('date', '<=', $filters['date_to']);
        }
    }
}
