<?php

namespace App\Services\OrganizerReports\Generators;

use App\Models\Host;
use App\Models\User;
use App\Services\OrganizerReports\Contracts\ReportGenerator;
use App\Services\Reports\Concerns\ExportsTabularReport;
use Illuminate\Database\Eloquent\Builder;
use Symfony\Component\HttpFoundation\Response;

class HostsReport implements ReportGenerator
{
    use ExportsTabularReport;

    public function generate(User $user, array $fields, array $filters, string $format): Response
    {
        $query = Host::query()
            ->createdByOrganizer((int) $user->id)
            ->withCount('events')
            ->latest();

        $this->applyFilters($query, $filters);

        $records = $query->limit(5000)->get();
        $fieldKeys = $fields !== [] ? $fields : array_keys(config('organizer_reports.reports.hosts.fields', []));
        $fieldLabels = config('organizer_reports.reports.hosts.fields', []);

        $headers = [];
        foreach ($fieldKeys as $key) {
            $headers[] = $fieldLabels[$key] ?? $key;
        }

        $rows = $records->map(function (Host $host) use ($fieldKeys) {
            $values = [
                'id' => $host->id,
                'name' => $host->name,
                'email' => $host->email ?? '—',
                'contact_number' => $host->contact_number ?? '—',
                'events_count' => (int) ($host->events_count ?? 0),
                'is_active' => $host->is_active ? 'Yes' : 'No',
                'created_at' => $host->created_at?->format('Y-m-d H:i') ?? '—',
            ];

            return array_map(fn ($key) => $values[$key] ?? '—', $fieldKeys);
        })->all();

        $title = 'Organizer Hosts Report';

        if ($format === 'csv') {
            return $this->downloadCsv($title, $headers, $rows, 'organizer-hosts');
        }

        return $this->downloadPdfTable($title, $headers, $rows, 'organizer-hosts', [
            ['label' => 'Total rows', 'value' => count($rows)],
            ['label' => 'Generated by', 'value' => $this->userDisplayName($user)],
            ...$this->dateRangeSummary($filters, 'Created'),
        ]);
    }

    /**
     * @param  array<string, mixed>  $filters
     */
    private function applyFilters(Builder $query, array $filters): void
    {
        $q = trim((string) ($filters['q'] ?? ''));
        if ($q !== '') {
            $query->where(function (Builder $inner) use ($q) {
                $inner->where('name', 'like', "%{$q}%")
                    ->orWhere('email', 'like', "%{$q}%")
                    ->orWhere('contact_number', 'like', "%{$q}%");
            });
        }

        if (isset($filters['active']) && $filters['active'] !== '') {
            $query->where('is_active', (bool) (int) $filters['active']);
        }

        if (! empty($filters['date_from'])) {
            $query->whereDate('created_at', '>=', $filters['date_from']);
        }

        if (! empty($filters['date_to'])) {
            $query->whereDate('created_at', '<=', $filters['date_to']);
        }
    }
}
