<?php

namespace App\Services\OrganizerReports\Generators;

use App\Enums\PaymentStatusEnum;
use App\Models\Payment;
use App\Models\User;
use App\Services\OrganizerReports\Contracts\ReportGenerator;
use App\Services\Reports\Concerns\ExportsTabularReport;
use Illuminate\Database\Eloquent\Builder;
use Symfony\Component\HttpFoundation\Response;

class PaymentsReport implements ReportGenerator
{
    use ExportsTabularReport;

    public function generate(User $user, array $fields, array $filters, string $format): Response
    {
        $organizerId = (int) $user->id;

        $query = Payment::query()
            ->with(['user:id,first_name,last_name,email'])
            ->whereHas(
                'ticketBookings.event',
                fn (Builder $event) => $event->createdByOrganizer($organizerId)
            )
            ->latest();

        $this->applyFilters($query, $filters, $organizerId);

        $records = $query->limit(5000)->get();
        $fieldKeys = $fields !== [] ? $fields : array_keys(config('organizer_reports.reports.payments.fields', []));
        $fieldLabels = config('organizer_reports.reports.payments.fields', []);

        $headers = [];
        foreach ($fieldKeys as $key) {
            $headers[] = $fieldLabels[$key] ?? $key;
        }

        $rows = $records->map(function (Payment $payment) use ($fieldKeys) {
            $values = [
                'id' => $payment->id,
                'reference' => $payment->reference ?? '—',
                'buyer' => $this->userDisplayName($payment->user),
                'email' => $payment->user?->email ?? '—',
                'amount' => number_format((float) $payment->amount, 2, '.', ''),
                'currency' => strtoupper((string) ($payment->currency ?? 'LKR')),
                'status' => $payment->status instanceof PaymentStatusEnum
                    ? ucfirst($payment->status->value)
                    : (string) $payment->status,
                'payment_method' => $payment->payment_method?->value ?? '—',
                'purpose' => $payment->purpose ?? '—',
                'created_at' => $payment->created_at?->format('Y-m-d H:i') ?? '—',
            ];

            return array_map(fn ($key) => $values[$key] ?? '—', $fieldKeys);
        })->all();

        $title = 'Organizer Payments Report';

        if ($format === 'csv') {
            return $this->downloadCsv($title, $headers, $rows, 'organizer-payments');
        }

        return $this->downloadPdfTable($title, $headers, $rows, 'organizer-payments', [
            ['label' => 'Total rows', 'value' => count($rows)],
            ['label' => 'Generated by', 'value' => $this->userDisplayName($user)],
        ]);
    }

    /**
     * @param  array<string, mixed>  $filters
     */
    private function applyFilters(Builder $query, array $filters, int $organizerId): void
    {
        $q = trim((string) ($filters['q'] ?? ''));
        if ($q !== '') {
            $query->where(function (Builder $inner) use ($q) {
                $inner->where('reference', 'like', "%{$q}%")
                    ->orWhere('stripe_session_id', 'like', "%{$q}%")
                    ->orWhereHas('user', function (Builder $userQuery) use ($q) {
                        $userQuery->where('email', 'like', "%{$q}%")
                            ->orWhere('first_name', 'like', "%{$q}%")
                            ->orWhere('last_name', 'like', "%{$q}%");
                    });
            });
        }

        if (! empty($filters['status'])) {
            $query->where('status', $filters['status']);
        }

        if (! empty($filters['event_id'])) {
            $eventId = (int) $filters['event_id'];
            $query->whereHas('ticketBookings', function (Builder $booking) use ($eventId, $organizerId) {
                $booking->where('event_id', $eventId)
                    ->whereHas('event', fn (Builder $event) => $event->createdByOrganizer($organizerId));
            });
        }

        if (! empty($filters['date_from'])) {
            $query->whereDate('created_at', '>=', $filters['date_from']);
        }

        if (! empty($filters['date_to'])) {
            $query->whereDate('created_at', '<=', $filters['date_to']);
        }
    }
}
