<?php

namespace App\Services\OrganizerReports\Generators;

use App\Models\Rating;
use App\Models\User;
use App\Services\OrganizerReports\Contracts\ReportGenerator;
use App\Services\Reports\Concerns\ExportsTabularReport;
use Illuminate\Database\Eloquent\Builder;
use Symfony\Component\HttpFoundation\Response;

class ReviewsReport implements ReportGenerator
{
    use ExportsTabularReport;

    public function generate(User $user, array $fields, array $filters, string $format): Response
    {
        $query = Rating::query()
            ->with(['user:id,first_name,last_name,email', 'event:id,name'])
            ->whereHas('event', fn (Builder $q) => $q->createdByOrganizer((int) $user->id))
            ->latest('ratings.created_at');

        $this->applyFilters($query, $filters);

        $records = $query->limit(5000)->get();
        $fieldKeys = $fields !== [] ? $fields : array_keys(config('organizer_reports.reports.reviews.fields', []));
        $fieldLabels = config('organizer_reports.reports.reviews.fields', []);

        $headers = [];
        foreach ($fieldKeys as $key) {
            $headers[] = $fieldLabels[$key] ?? $key;
        }

        $rows = $records->map(function (Rating $rating) use ($fieldKeys) {
            $values = [
                'id' => $rating->id,
                'event' => $rating->event?->name ?? '—',
                'reviewer' => $this->userDisplayName($rating->user),
                'email' => $rating->user?->email ?? '—',
                'score' => $rating->score,
                'submitted_at' => $rating->created_at?->format('Y-m-d H:i') ?? '—',
            ];

            return array_map(fn ($key) => $values[$key] ?? '—', $fieldKeys);
        })->all();

        $title = 'Organizer Reviews Report';

        if ($format === 'csv') {
            return $this->downloadCsv($title, $headers, $rows, 'organizer-reviews');
        }

        return $this->downloadPdfTable($title, $headers, $rows, 'organizer-reviews', [
            ['label' => 'Total rows', 'value' => count($rows)],
            ['label' => 'Generated by', 'value' => $this->userDisplayName($user)],
        ]);
    }

    /**
     * @param  array<string, mixed>  $filters
     */
    private function applyFilters(Builder $query, array $filters): void
    {
        if (! empty($filters['event_id'])) {
            $query->where('event_id', (int) $filters['event_id']);
        }

        if (! empty($filters['score'])) {
            $query->where('score', (int) $filters['score']);
        }

        if (! empty($filters['date_from'])) {
            $query->whereDate('ratings.created_at', '>=', $filters['date_from']);
        }

        if (! empty($filters['date_to'])) {
            $query->whereDate('ratings.created_at', '<=', $filters['date_to']);
        }

        $q = trim((string) ($filters['q'] ?? ''));
        if ($q !== '') {
            $query->where(function (Builder $inner) use ($q) {
                $inner->whereHas('user', function (Builder $userQuery) use ($q) {
                    $userQuery->where('email', 'like', "%{$q}%")
                        ->orWhere('first_name', 'like', "%{$q}%")
                        ->orWhere('last_name', 'like', "%{$q}%");
                })->orWhereHas('event', function (Builder $eventQuery) use ($q) {
                    $eventQuery->where('name', 'like', "%{$q}%");
                });
            });
        }
    }
}
