<?php

namespace App\Services\OrganizerReports\Generators;

use App\Models\User;
use App\Services\OrganizerReports\Contracts\ReportGenerator;
use App\Services\OrganizerSalesService;
use App\Services\Reports\Concerns\ExportsTabularReport;
use Symfony\Component\HttpFoundation\Response;

class SalesReport implements ReportGenerator
{
    use ExportsTabularReport;

    public function __construct(
        protected OrganizerSalesService $salesService,
    ) {}

    public function generate(User $user, array $fields, array $filters, string $format): Response
    {
        $serviceFilters = [
            'search' => $filters['q'] ?? null,
            'event_id' => ! empty($filters['event_id']) ? (int) $filters['event_id'] : null,
            'status' => $filters['status'] ?? null,
            'from_date' => $filters['date_from'] ?? null,
            'to_date' => $filters['date_to'] ?? null,
        ];

        $sales = $this->salesService->all((int) $user->id, $serviceFilters);
        $fieldKeys = $fields !== [] ? $fields : array_keys(config('organizer_reports.reports.sales.fields', []));
        $fieldLabels = config('organizer_reports.reports.sales.fields', []);

        $headers = [];
        foreach ($fieldKeys as $key) {
            $headers[] = $fieldLabels[$key] ?? $key;
        }

        $rows = collect($sales)->map(function (array $sale) use ($fieldKeys) {
            $values = [
                'ticket_number' => $sale['ticket_number'] ?? '',
                'event' => $sale['event'] ?? '—',
                'category' => $sale['category'] ?? '—',
                'amount' => number_format((float) ($sale['amount'] ?? 0), 2, '.', ''),
                'original_amount' => number_format((float) ($sale['original_amount'] ?? $sale['amount'] ?? 0), 2, '.', ''),
                'refund_amount' => number_format((float) ($sale['refund_amount'] ?? 0), 2, '.', ''),
                'purchased_at' => $sale['booked_at_formatted'] ?? '—',
                'check_in_status' => $sale['check_in_status'] ?? '—',
                'status' => $sale['status'] ?? '—',
            ];

            return array_map(fn ($key) => $values[$key] ?? '—', $fieldKeys);
        })->all();

        $title = 'Organizer Sales Report';

        if ($format === 'csv') {
            return $this->downloadCsv($title, $headers, $rows, 'organizer-sales');
        }

        return $this->downloadPdfTable($title, $headers, $rows, 'organizer-sales', [
            ['label' => 'Total rows', 'value' => count($rows)],
            ['label' => 'Generated by', 'value' => $this->userDisplayName($user)],
        ]);
    }
}
